### ISSUE TITLE
Won't save files

### ISSUE THREAD

**Issue by vgteig** [nicrivard/readwise2directory#10]
Hi,

I've downloaded your kit, and I get it to sync with the readwise library, but It won't save any files on my pc. Do you know what could be the problem?

Best regards, vgteig.

**Comment by nicrivard** [comment]
Hey @vgteig - thanks for giving this a go! Hmm there could be several things going on...

Are you seeing any error messages in your terminal / command prompt, or `readwise-directory.log`? That would help to troubleshoot the issue.

Have you specified all the required variables in `readwiseMetadata.py`? If notes aren't saving, then perhaps it's because there's no `targetDirectory` specified? 

What operating system are you running? I've tested this on Mac OS and Windows, so perhaps there are issues with others (e.g. Linux)?

**Comment by nicrivard** [comment]
Oh I just noticed you closed the issue 😅 Hopefully that means everything is working as expected 👍
