### ISSUE TITLE
Including source URL in YAML header

### ISSUE THREAD

**Issue by carmensandoval** [nicrivard/readwise2directory#7]
Hey Nic,

Trying to figure out how to include the source URL.

I do a lot of highlighting of academic papers, and it's useful to have the URL to the article itself when going over highlights. 

From the Readwise API docs, it looks like the parameter is `source_url` ?

`source_url | string | The url of the article/podcast (the "source")`

Currently the script only appends the `Readwise URL`. Readwise's Roam integation does include the source URL, though.

Thanks again!
Carmen

<img width="990" alt="Obsidian_20210118_19 07 50" src="https://user-images.githubusercontent.com/10520084/104982897-79622480-59c0-11eb-8a89-63ab21bc992a.png">

Readwise -> Roam example:

![image](https://user-images.githubusercontent.com/10520084/104983210-2f2d7300-59c1-11eb-886c-be21e437d4c9.png)

**Comment by nicrivard** [comment]
Hey @carmensandoval - thank you for the feedback. 

Unfortunately, `source_url` is not available when fetching books or highlights from Readwise, only when creating new ones via the API. (You’ll see that field is listed under `Highlight CREATE`) 

This is also something I’d like to see, so I’ve emailed the founders who said they will look into it. 

As a temporary workaround, with [release v1.5](https://github.com/nicrivard/readwise2directory/releases/tag/v1.5) I’ve included cover images beneath the note title which when clicked will hyperlink you back to the Readwise book URL , and from there the `source_url` is included beneath the book title. So, effectively an easy 2-step process  rather than 1-step.

I’ll let you know if / when the Readwise team come back to me with a definitive about including `source_url` as an available field to fetch from the API. 

Thanks again for the feedback, and hope you’re enjoying the script otherwise!

**Comment by nicrivard** [comment]
Hey @carmensandoval, I am very pleased to say that the Readwise team have updated their API to expose `source_url` as a field to fetch from `Books LIST`, so I have updated the script as part of [release v1.6](https://github.com/nicrivard/readwise2directory/releases/tag/v1.6) to include this in the YAML data and markdown note.

Hope you enjoy!

**Comment by carmensandoval** [comment]
Thanks @nicrivard ! This is awesome. 🙌  Sorry I missed this earlier!
